version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports: ["3000:3000"]
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/ohmpatel/data/
    ports: ["5432:5432"]
    expose:
      - '5432'
volumes:
  data: